[inductor] Promote half-precision CPU constants to float
Currently `aten.where` can fail with the following C++ compiler error:
```
error: operands to '?:' have different types 'c10::Half' and 'float'
```

This happens because `ops.load` is overridden to cast Half inputs to float, but
`ops.constant` will load a Half without promoting to float.

ghstack-source-id: 603d1424ad85fcf2ae89c6d355f86bf11ac5ff66
Pull Request resolved: https://github.com/pytorch/pytorch/pull/91224