Check SM version before calling flash attention with BFloat16
The flash attention code path requires sm80 or newer to run on
BFloat16, so any OpInfo tests running with BFloat16 would fail with
the error:
```
RuntimeError: Expected q_dtype == at::kHalf || (is_sm8x && q_dtype == at::kBFloat16) to be true, but got false.
```

ghstack-source-id: 33bf11207ec7364bc53c63ae5770ce84892dd8ef
Pull Request resolved: https://github.com/pytorch/pytorch/pull/86560